### ISSUE TITLE
Missing Examples for motility test

### ISSUE THREAD

**Issue by robotiko** [calquezar/OpenCASA#1]
Hi, 
according to the test manual, there should be a folder with test examples for motility but it seems to be the only one missing in the Test_data folder.

**Comment by calquezar** [comment]
Hi robotiko,
you will find the the complete test files at https://doi.org/10.6084/m9.figshare.7247039.v1. I found a problem with the size of the files and my github storage limit and I did not upload the videos here.

**Comment by robotiko** [comment]
Solved!
thanks a lot.
Playtime! ;)
