### ISSUE TITLE
No results/ error running under ij152-win-java8.zip (1.52o version)

### ISSUE THREAD

**Issue by robotiko** [calquezar/OpenCASA#2]
Tried with ImageJ 1.52o and runs but no screens is displayed with results after calculating tracks.

**Comment by calquezar** [comment]
I recommend you to visit the google group https://groups.google.com/d/forum/opencasa_mailinglist. There you will find a bigger group to ask and find answers. For the moment, I suggest to try to the ImageJ and OS version mentioned in the paper.

**Comment by robotiko** [comment]
It might be a dependency not included. 
Just installed FIJI and all worked with no issues. 

BTW, Google group seems to be private. Gives a permission error just trying to access.

**Comment by calquezar** [comment]
Hi robotiko,
sorry for the late responde :s I just see right now the comment. Have you been able to access the google group? We fixed that problem. Please let me know if you are a member of the group. In other case I can give you access. 

Best
Carlos
